services:

  # ============================================================
  # FASTAPI
  # ============================================================

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: datapulse-api

    ports:
      - "8000:8000"

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000

    depends_on:
      - mlflow

    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./scripts:/app/scripts

    restart: unless-stopped


  # ============================================================
  # MLFLOW
  # ============================================================

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest

    container_name: datapulse-mlflow

    ports:
      - "5000:5000"

    volumes:
      - ./mlruns:/mlruns

    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlruns/mlflow.db
      --default-artifact-root /mlruns

    restart: unless-stopped