name: MLOPS DATAPULSE - Docker Compose CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:

  docker-compose-test:

    runs-on: ubuntu-latest

    steps:

      # ---------------------------------------------------------
      # 1. Checkout
      # ---------------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4


      # ---------------------------------------------------------
      # 2. Docker Buildx
      # ---------------------------------------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      # ---------------------------------------------------------
      # 3. Login Docker Hub
      # ---------------------------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # ---------------------------------------------------------
      # 4. Validate Docker Compose
      # ---------------------------------------------------------
      - name: Validate Docker Compose
        run: |
          docker compose config


      # ---------------------------------------------------------
      # 5. Build all services
      # ---------------------------------------------------------
      - name: Build Docker Compose services
        run: |
          docker compose build


      # ---------------------------------------------------------
      # 6. Start all services
      # ---------------------------------------------------------
      - name: Start Docker Compose
        run: |
          docker compose up -d


      # ---------------------------------------------------------
      # 7. Show containers
      # ---------------------------------------------------------
      - name: Check running containers
        run: |
          docker compose ps


      # ---------------------------------------------------------
      # 8. Wait for services
      # ---------------------------------------------------------
      - name: Wait for services
        run: |
          echo "Waiting for services..."
          sleep 15


      # ---------------------------------------------------------
      # 9. Show logs
      # ---------------------------------------------------------
      - name: Show Docker Compose logs
        if: always()
        run: |
          docker compose logs --no-color


      # ---------------------------------------------------------
      # 10. Test FastAPI
      # ---------------------------------------------------------
      - name: Test FastAPI
        run: |
          curl --fail http://localhost:8000/docs


      # ---------------------------------------------------------
      # 11. Test MLflow
      # ---------------------------------------------------------
      # - name: Test MLflow
      #   run: |
      #     curl --fail http://localhost:5000


      # ---------------------------------------------------------
      # 12. Stop containers
      # ---------------------------------------------------------
      - name: Stop Docker Compose
        if: always()
        run: |
          docker compose down -v

